name: Publish

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/cache/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build Jekyll site
        run: |
          mv docker-compose.ci.yml docker-compose.override.yml
          docker compose run --rm web /bin/bash -c "(bundle check || bundle install --jobs=3) && JEKYLL_ENV=production bundle exec jekyll build"
      - name: Publish to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        run: ./_scripts/push-to-gh-pages.sh
      - name: Upload English content
        uses: actions/upload-artifact@v4
        with:
          name: english-content
          path: build/i18n-en.json

  publish_to_lokalise:
    runs-on: ubuntu-24.04
    needs: build_and_deploy
    steps:
      - name: Download English content
        uses: actions/download-artifact@v4
        with:
          name: english-content
      - name: Push English content to Lokalise
        uses: manastech/lokalise-file-push@ftc
        with:
          api-token: ${{ secrets.LOCALIZE_TOKEN }}
          project-id: 423383895e6b8c4b081a89.98184174
          file-path: english-content/i18n-en.json
